### ISSUE TITLE
Do not use `gradle/actions/setup-gradle` with `arguments`; replace with two steps

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-github-actions#100]
## What problem are you trying to solve?

> **Using the action to execute Gradle via the arguments parameter is deprecated**
> The core functionality of the setup-gradle (and gradle-build-action) actions is to configure your Gradle environment for GitHub Actions. Once the action has run, any subsequent Gradle executions will benefit from caching, reporting and other features of the action.
> 
> Using the arguments parameter to execute Gradle directly is not necessary to benefit from this action. This input is deprecated, and will be removed in the v4 major release of the action.
> 
> To convert your workflows, replace any steps using the arguments parameter with 2 steps: one to setup-gradle and another that runs your Gradle build.

\https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#using-the-action-to-execute-gradle-via-the-arguments-parameter-is-deprecated

## What precondition(s) should be checked before applying this recipe?
Uses `gradle/actions/setup-gradle`

## Describe the situation before applying the recipe

```yaml
steps:
- name: Assemble the project
  uses: gradle/actions/setup-gradle@v3
  with:
    arguments: 'assemble'

 - name: Run the tests
   uses: gradle/actions/setup-gradle@v3
   with:
     arguments: 'test'

 - name: Run build in a subdirectory
   uses: gradle/actions/setup-gradle@v3
   with:
     build-root-directory: another-build
     arguments: 'build'
```

## Describe the situation after applying the recipe

```yaml
- name: Setup Gradle
  uses: gradle/actions/setup-gradle@v3

- name: Assemble the project
  run: ./gradlew assemble

- name: Run the tests
  run: ./gradlew test

- name: Run build in a subdirectory
  working-directory: another-build
  run: ./gradlew build
```

## Any additional context

> Using the action in this way gives you more control over how Gradle is executed, while still giving you all of the benefits of the setup-gradle action.
> 
> The arguments parameter is scheduled to be removed in setup-gradle@v4.
> 
> Note: if you are using the gradle-build-action, [see here](https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#the-action-gradlegradle-build-action-has-been-replaced-by-gradleactionssetup-gradle) for more details on how to migrate.
