### ISSUE TITLE
Add `merge_group` build trigger

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-github-actions#114]
## What problem are you trying to solve?

Add the `merge_group` trigger to a build so that builds are triggered in the merge queue

## What precondition(s) should be checked before applying this recipe?

Merge queues need to be enabled the repository settings, but that may be out of the scope of this project

## Describe the situation before applying the recipe

```yml
on:
  pull_request:
```

## Describe the situation after applying the recipe

```yml
on:
  pull_request:
  merge_group:
```

## Any additional context

The generic recipe https://github.com/openrewrite/rewrite-github-actions/issues/90 could be used to accomplish this but as that recipe will be more involved, we can deliver this independently  first. 

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue

**Comment by yeikel** [comment]
@timtebeek What are your thoughts about delivering this before #90?

**Comment by timtebeek** [comment]
Should be manageable I think; at first glance it's no more than providing a named recipe that applies MergeYaml to add in that `merge_group` in `$.on`, very similar to what we've done here:

https://github.com/openrewrite/rewrite-github-actions/blob/5c36536950e5da9d717ba80d1dbb295f72308dbd/src/main/resources/META-INF/rewrite/github.yml#L17-L29

Welcome to push that up! 🙏🏻

**Comment by timtebeek** [comment]
Still open and still the smallest win on the board. Sketch, following the `AddManualTrigger` pattern in `github.yml`:

```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.github.AddMergeGroupTrigger
displayName: Add `merge_group` workflow trigger
description: Trigger workflows for pull requests queued in a [merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue).
tags:
  - github
recipeList:
  - org.openrewrite.yaml.MergeYaml:
      key: $.on
      yaml: |-
        merge_group:
      acceptTheirs: true
      fileMatcher: ".github/workflows/*.{yml,yaml}"
```

Probably wants a precondition so it only applies to workflows that already have a `pull_request` trigger.
