### ISSUE TITLE
Replace usage of arrays when there is a single item in the dependency list

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-github-actions#128]
## What problem are you trying to solve?

Improve readability of the workflow

## What precondition(s) should be checked before applying this recipe?

There is one single item within the `needs` block and an array is used

The recipe should not be applied if there are multiple entries 

```yml

  docker-build:
    needs: [ maven, slack ]
    uses: ...

```

## Describe the situation before applying the recipe

```yml

  docker-build:
    needs: [ maven ]
    uses: ...

```

## Describe the situation after applying the recipe

```yml

  docker-build:
    needs: maven
    uses: ...

```
