### ISSUE TITLE
Replace usage of `flow style` with `block style` for job dependency

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-github-actions#129]
## What problem are you trying to solve?

- Prefer the usage of the block style as it improves readability
- Source control of  Block Style blocks is also easier 

## What precondition(s) should be checked before applying this recipe?

**Flow Style:** Uses square brackets [] for arrays. Example: items: `[item1, item2, item3]`

**Block Style**: Uses new lines and indentation for arrays and objects

```yml
items:
  - item1
  - item2
  - item3

```
## Describe the situation before applying the recipe

```yml

  job:
    needs: [ dependency_1, dependency_2, dependency_3, dependency_4, dependency_5... ]
    uses: ...
```

## Describe the situation after applying the recipe

```yml

  job:
    needs: 
       - dependency_1
       -  dependency_2
       - dependency_3
       - dependency_4
       - dependency_5
    uses: ...
```

## Any additional context

https://www.yaml.info/learn/flowstyle.html
https://syedrakib.medium.com/block-style-yaml-vs-flow-style-yaml-a42eb1082202
