### ISSUE TITLE
Remove workflow input

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-github-actions#132]
## What problem are you trying to solve?

I discontinued the use of an input in my reusable workflow and need to update all its usages to reflect the change.

## What precondition(s) should be checked before applying this recipe?

- The specific workflow and version is configured
- The input to remove is used in the workflow

## Describe the situation before applying the recipe

```yml

name: Deployment
run-name: e3-${{ github.event.inputs.image }}

on:
  workflow_dispatch:
    inputs:
      project:
        type: string
        description: 'A description'
        required: true
        default: ''
      myInputToRemove:
        type: string
        description: 'A description'
        required: true
        default: ''

jobs:

  deploy-dev
    name: "_"
    uses: org/repo/.github/workflows/myWorkflow.yml@version
    secrets: inherit
    with:
      project: ${{ github.event.inputs.project}}
      myInputToRemove: ${{ github.event.inputs.myInputToRemove}}

 deploy-qa
    name: "_"
    uses: org/repo/.github/workflows/myWorkflow.yml@version
    secrets: inherit
    with:
      project: ${{ github.event.inputs.project}}
      myInputToRemove: ${{ github.event.inputs.myInputToRemove}}

```

## Describe the situation after applying the recipe

```yml

name: Deployment
run-name: e3-${{ github.event.inputs.image }}

on:
  workflow_dispatch:
    inputs:
      project:
        type: string
        description: 'A description'
        required: true
        default: ''


jobs:

  deploy-dev
    name: "_"
    uses: org/repo/.github/workflows/myWorkflow.yml@version
    secrets: inherit
    with:
      project: ${{ github.event.inputs.project}}

 deploy-qa
    name: "_"
    uses: org/repo/.github/workflows/myWorkflow.yml@version
    secrets: inherit
    with:
      project: ${{ github.event.inputs.project}}

```
