### ISSUE TITLE
Recipe  - Update version of an action

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-github-actions#23]
Example: Update `actions/checkout` to `V3`

```yml


name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
```

```yml


name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
```

We should be able to do this with the built in [foundational YML recipe](https://docs.openrewrite.org/reference/recipes/yaml/changevalue) but I believe that there is still value in having this pre-configured as it is generic enough
