### ISSUE TITLE
Recipe - Replace runners

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-github-actions#25]
```yml

jobs:
  build:
    runs-on: ubuntu-latest
  other:
    runs-on: ubuntu-latest
```

Input to the recipe: 

- Job : jobs.build
- New runner : MyNewRunner

```yml
jobs:
  build:
    runs-on: MyNewRunner
  other:
    runs-on: ubuntu-latest
```

Ideally, and to avoid creating another recipe, it should support adding multiple runners: 

- Job : jobs.build
- New runner : MyNewRunner,MyNewRunner2

```yml
jobs:
  build:
    runs-on:  [MyNewRunner1,MyNewRunner2]
```
