### ISSUE TITLE
Use runner groups and labels

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-github-actions#26]
This recipe should remove the individual runner and use the runner group instead. It should also `label` as an optional parameter

```yml
jobs:
  build:
    runs-on: ubuntu-latest
  other:
    runs-on: ubuntu-latest
```

Input to the recipe:

> Job : jobs.build
> Group : ubuntu-runners
> Labels: labels: ubuntu-20.04-16core

Output: 

```yml
jobs:
  build:
    group: ubuntu-runners
    labels: ubuntu-20.04-16core
  other:
    runs-on: ubuntu-latest
```

More info: https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job#choosing-runners-in-a-group
