### ISSUE TITLE
Replace action name but leave arguments and version untouched

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-github-actions#28]
Given the following input:

```yml

jobs:
  run:
    runs-on: ubuntu
    steps:
      - uses: org/action@version
        with:
         message: 'My Message'
```

> Path: jobs.run.steps[0]
> New name : MyOrg/OtherName@version

```yml

jobs:
  run:
    runs-on: ubuntu
    steps:
      - uses: MyOrg/OtherName@version
        with:
         message: 'My Message'
```
