### ISSUE TITLE
Add runners

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-github-actions#40]
Similar to https://github.com/openrewrite/rewrite-github-actions/issues/25 but it should add to an existing list of runners and not replace

- Job : jobs.other
- New runner : MyNewRunner, SomeOtherRunner

```yml

jobs:
  build:
    runs-on: ubuntu-latest
  other:
    runs-on: ubuntu-latest
```

Output: 

```yml
jobs:
  build:
    runs-on: MyNewRunner
  other:
    runs-on: [ubuntu-latest,MyNewRunner, SomeOtherRunner]
```
