### ISSUE TITLE
Prefer `Eclipse Temurin` when the build is in shared runners

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-github-actions#43]
See https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#hosted-tool-cache

Also https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

```yml
- uses: actions/setup-java@v3.9.0
        with:
          distribution: zulu
          java-version: 17
```

```yml
- uses: actions/setup-java@v3.9.0
        with:
          distribution: temurin
          java-version: 17
```
