### ISSUE TITLE
Remove specific cron trigger

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-github-actions#46]
Similar to #38, but this recipe should ask the user to specify which one to remove

We can potentially support #38 with this one if we allow wildcards as an input

Input:  "0 11 * * *"

```yml


            on:
              push:
                branches:
                  - main
              schedule:
                - cron: "0 18 * * *"
                - cron: "0 11 * * *"
```

Output : 
```yml
            on:
              push:
                branches:
                  - main
              schedule:
                - cron: "0 18 * * *"
```
