### ISSUE TITLE
Change Maven commands to use the maven wrapper

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-github-actions#57]
This recipe can be part of https://github.com/openrewrite/rewrite/issues/1565 and change all the maven references to the maven wrapper

Example: 

```yml
 name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

```

Unix runners: 

```yml
 name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build with Maven
        run: ./mvn --batch-mode --update-snapshots package

```
Windows Runners: 

```yml
 name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build with Maven
        run: mvn.cmd --batch-mode --update-snapshots package

```
