### ISSUE TITLE
Change Gradle commands to use the Gradle Wrapper 

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-github-actions#58]
Example: 

```yml
name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build with Maven
        run: gradle --batch-mode --update-snapshots package

```

Unix runners: 

```yml
name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build with Maven
        run: ./gradlew --batch-mode --update-snapshots package

```
Windows Runners: 

```yml
 name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build with Maven
        run: gradlew --batch-mode --update-snapshots package

```

Same as https://github.com/openrewrite/rewrite-github-actions/issues/57 but with the Gradle Wrapper
