### ISSUE TITLE
Remove `image` when the container block is empty

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-github-actions#78]
From: https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container

```yml

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:14.16     
```

```yml

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container: node:14.16
```

If there is more configuration within the `container` block, it should stay as is. Example: 

```yml

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:14.16
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

```
