### ISSUE TITLE
Modify the default permissions granted to `GITHUB_TOKEN` for a job

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-github-actions#79]
From https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

```yml

name: "My workflow"

on: [ push ]

permissions:
  actions: read|write|none
  checks: read|write|none
  contents: read|write|none
  deployments: read|write|none
  id-token: read|write|none
  issues: read|write|none
  discussions: read|write|none
  packages: read|write|none
  pages: read|write|none
  pull-requests: read|write|none
  repository-projects: read|write|none
  security-events: read|write|none
  statuses: read|write|none

jobs:

```

Example:

```yml

jobs:
  stale:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v5

```
