### ISSUE TITLE
Replace action but leave configuration as is

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-github-actions#80]
Define an action that replaces the `uses` keyword with a different action but leaves everything as is 

Example 

```yml

      - name: Cache Maven Download
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7
        with:
         path: ~/.m2/wrapper/dists
         key: ${{ runner.os }}-maven-${{ hashFiles('.mvn/wrapper/maven-wrapper.properties') }}
         restore-keys: ${{ runner.os }}-maven-installation-
```

```diff

      - name: Cache Maven Download
--    uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7
++    uses: myOrg/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7
        with:
         path: ~/.m2/wrapper/dists
         key: ${{ runner.os }}-maven-${{ hashFiles('.mvn/wrapper/maven-wrapper.properties') }}
         restore-keys: ${{ runner.os }}-maven-installation-
```

The goal is to handle relocations 

Example : https://github.com/marketplace/actions/retry-step#ownership
