### ISSUE TITLE
Add container to job

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-github-actions#81]
```yml

jobs:

  build:
    runs-on: ubuntu-latest
```

```diff
jobs:

  build:
    runs-on: ubuntu-latest
++  container: maniator/gh@sha256:0c716a2af918209926088fc0c1457394f741d40eeab8f45d22cbb1e096513210

```
