### ISSUE TITLE
Upgrade Python version used in actions/setup-python

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-github-actions#85]
## What problem are you trying to solve?
When upgrading to newer versions of Python, we should also upgrade the Python version used in [GitHub Actions setup-python](https://github.com/actions/setup-python).
We already have a similar recipe for Java: [SetupJavaUpgradeJavaVersion](https://github.com/openrewrite/rewrite-github-actions/blob/main/src/main/java/org/openrewrite/github/SetupJavaUpgradeJavaVersion.java)

## What precondition(s) should be checked before applying this recipe?
`actions/setup-python` is used at all, with a `python-version` who's value or range does not match the target Python version.

## Describe the situation before applying the recipe
```yaml
steps:
- uses: actions/checkout@v3
- uses: actions/setup-python@v4
  with:
    python-version: '3.10' 
- run: python my_script.py
```

## Describe the situation after applying the recipe
```yaml
steps:
- uses: actions/checkout@v3
- uses: actions/setup-python@v4
  with:
    python-version: '3.11' 
- run: python my_script.py
```

## Have you considered any alternatives or workarounds?
No.

## Any additional context
Might want to make sure we don't set a version when [`python-version-file`](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-the-python-version-file-input) is in use.

https://github.com/openrewrite/rewrite-migrate-python/issues/6
