### ISSUE TITLE
Use `secrets: inherit` 

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-github-actions#89]
## What precondition(s) should be checked before applying this recipe?

- This only applies to re-usable workflows 
- The secrets key-value pair must be the same (ie: there are no transformations or aliasing)

## Describe the situation before applying the recipe

```yml

  maven:
    uses: org/.github/workflows/maven.yml@main
    secrets:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.USERNAME }}

```

## Describe the situation after applying the recipe

```diff

  maven:
    uses: org/.github/workflows/maven.yml@main
+   secrets: inherit
-    secrets:
-     USERNAME: ${{ secrets.USERNAME }}
-      PASSWORD: ${{ secrets.USERNAME }}
```

This should be left untouched because the secrets are transformed : 

```yml

  maven:
    uses: org/.github/workflows/maven.yml@main
    secrets:
      MY_CUSTOM_USERNAME_KEY: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.USERNAME }}

```

## Any additional context

https://github.blog/changelog/2022-05-03-github-actions-simplify-using-secrets-with-reusable-workflows/
https://stackoverflow.com/questions/71524542/how-to-use-reusable-github-workflows-and-keep-secrets-in-a-single-place
