### ISSUE TITLE
Recipe to update job triggers

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-github-actions#90]
Create a recipe to update the `types` for which a job can be triggered 

Examples : 

Input : 

```yml

name: "My job"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
```

Remove entry

```diff
on:
  pull_request:
    types:
      - opened
      - edited
-      - synchronize
```

Add entry: 

```diff
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
+    - closed
```

Add new type: 

```diff
on:
+  pull_request_review:
+    types: [edited, dismissed]
  pull_request:
    types:
      - opened
      - edited
      - synchronize
```

As there are many possible options here, we should probably have a generic recipe that accepts a `yml` expression and replaces the `on` block with it
